### PR TITLE
Modified data source and moved modeler plugins

### PR DESCRIPTION
**Pull request by Mattikin**
Modified data source to use dictionaries for the data points, rather
than duplicated code
Moved the modeler plugins into the "python" subfolder
Fixed icon and made some minor changes to the zenpack.yaml

### CODE REVIEW

**Comment by Mattikin** [comment]
Also removed the performanceSource and instance properties from the data source

**Comment by jcurry** [comment]
Many thanks for this - good stuff!
I have pulled you stuff, tweaked a couple of things like:

Added the top-level VMware Reports to objects.xml
Updated the README
Changed any '' in zenpack.yaml to ""
Updated version to 3.0.1

I have now pushed back to my master.

A comment from the customer who started all this off....

Some of the data values appear to be double what they are in your 
original ZenPack.  Same devices being monitored by old and new.  In the 
new, we have memory (memUsage) reading at well over 100%.  Any way you 
can check whether you are also seeing bad values?  It's all a bit hard 
as some of the values probably will change significantly from moment to 
moment so comparing graphs from old / new ZenPacks is not going to be at 
all an exact science; however, I am guessing I have something wrong with 
memUsage values over 100% :(

Any input appreciated.

Cheers,
Jane

On 05/10/15 21:42, Mattikin wrote:

> Modified data source to use dictionaries for the data points, rather
> then duplicated code
> Moved the modeler plugins into the "python" subfolder
> Fixed icon and made some minor changes to the zenpack.yaml
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1
> 
> ```
>     Commit Summary
> ```
> - Modified data source and moved modeler plugins
>   
>   ```
>   File Changes
>   ```
> - _D_ ZenPacks/community/VMwareESXiMonitorPython/.zenpack.yaml.swp
>   https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1/files#diff-0
>   (0)
> - _M_
>   ZenPacks/community/VMwareESXiMonitorPython/datasources/VMwareDataSource.py
>   https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1/files#diff-1
>   (190)
> - _R_
>   ZenPacks/community/VMwareESXiMonitorPython/modeler/plugins/community/python/VMwareESXiDatastoreMap.py
>   https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1/files#diff-2
>   (2)
> - _R_
>   ZenPacks/community/VMwareESXiMonitorPython/modeler/plugins/community/python/VMwareESXiGuestMap.py
>   https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1/files#diff-3
>   (2)
> - _R_
>   ZenPacks/community/VMwareESXiMonitorPython/modeler/plugins/community/python/VMwareESXiHostMap.py
>   https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1/files#diff-4
>   (2)
> - _R_
>   ZenPacks/community/VMwareESXiMonitorPython/modeler/plugins/community/python/VMwareESXiInterfaceMap.py
>   https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1/files#diff-5
>   (2)
> - _R_
>   ZenPacks/community/VMwareESXiMonitorPython/modeler/plugins/community/python/**init**.py
>   https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1/files#diff-6
>   (0)
> - _M_
>   ZenPacks/community/VMwareESXiMonitorPython/resources/ESXiHost.js
>   https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1/files#diff-7
>   (234)
> - _M_ ZenPacks/community/VMwareESXiMonitorPython/zenpack.yaml
>   https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1/files#diff-8
>   (24)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1.patch
> - https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1.

## 

Zenoss Master, Tivoli Certified Consultant & Instructor
Skills 1st Limited, 2 Cedar Chase, Taplow, Bucks, SL6 0EU, UK.
Registered in England & Wales, Company No. 3458854.
Tel: +44 (0)1628 782565      Skype: jane_curry_uk
Email: jane.curry@skills-1st.co.uk   Web: http://www.skills-1st.co.uk
Copyright (c) 2015 Jane Curry < jane.curry@skills-1st.co.uk >.  All rights reserved.

**Comment by Mattikin** [comment]
Hey Jane,

I've looked into this and in my case the values reported by the old and new ZenPack are exactly the same.

However I'm also using the modified data source. So maybe you can ask your customer to upgrade to the latest version?

Also a good way to compare:
In the new data source uncomment line 388-390 and run in debug mode
In a second putty session run the esxi_monitor perl script (you only need the vSphere SDK for perl + script, no need to actually install the old ZenPack. As a matter of fact you don't even need Zenoss)
You can run it like this:
/usr/bin/perl esxi_monitor.pl --server <ESXi-Host-Name-or-IP> --username <username> --password '<password>' --options 'guestperf:<VM-Name>'

I ran the new data source and the perl script at the same time and received the exact same output:

{'adminStatus': 1, 'operStatus': 1, 'memUsage': 5.99, 'cpuUsageMin': 0.54, 'cpuUsageMax': 0.54, 'cpuUsageAvg': 0.54, 'cpuUsage': 57000000.0, 'memOverhead': 70447104.0, 'memConsumed': 1986183168.0, 'diskUsage': 14336.0, 'powerState': 'poweredOn', 'overallStatus': 'green'}

memUsage=5.99 memOverhead=70447104 memConsumed=1986183168 diskUsage=14336 cpuUsageMin=0.54 cpuUsageMax=0.54 cpuUsageAvg=0.54 cpuUsage=57000000 adminStatus=1 operStatus=1

BTW: While I was testing this I've also noticed that you're adding the "powerState" and "overallStatus" to the results dictionary, even though there are no data points for those values.
Are you doing this for debugging purposes?

**Comment by jcurry** [comment]
Thanks for the testing ideas - I had started investigating along the 
same lines.  I have clearance to install the new version of the ZP 
tomorrow morning so will report back.

The powerState and overallStatus weren't really there for any good 
reason so I guess we could lose them.

Talk to you again tomorrow - it will be late afternoon (UK) as I need to 
be with a customer most of the day.

Cheers,
Jane

On 13/10/15 22:07, Mattikin wrote:

> Hey Jane,
> 
> I've looked into this and in my case the values reported by the old 
> and new ZenPack are exactly the same.
> 
> However I'm also using the modified data source. So maybe you can ask 
> your customer to upgrade to the latest version?
> 
> Also a good way to compare:
> In the new data source uncomment line 388-390 and run in debug mode
> In a second putty session run the esxi_monitor perl script (you only 
> need the vSphere SDK for perl + script, no need to actually install 
> the old ZenPack. As a matter of fact you don't even need Zenoss)
> You can run it like this:
> /usr/bin/perl esxi_monitor.pl --server --username --password '' 
> --options 'guestperf:'
> 
> I ran the new data source and the perl script at the same time and 
> received the exact same output:
> 
> {'adminStatus': 1, 'operStatus': 1, 'memUsage': 5.99, 'cpuUsageMin': 
> 0.54, 'cpuUsageMax': 0.54, 'cpuUsageAvg': 0.54, 'cpuUsage': 
> 57000000.0, 'memOverhead': 70447104.0, 'memConsumed': 1986183168.0, 
> 'diskUsage': 14336.0, 'powerState': 'poweredOn', 'overallStatus': 'green'}
> 
> memUsage=5.99 memOverhead=70447104 memConsumed=1986183168 
> diskUsage=14336 cpuUsageMin=0.54 cpuUsageMax=0.54 cpuUsageAvg=0.54 
> cpuUsage=57000000 adminStatus=1 operStatus=1
> 
> BTW: While I was testing this I've also noticed that you're adding the 
> "powerState" and "overallStatus" to the results dictionary, even 
> though there are no data points for those values.
> Are you doing this for debugging purposes?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1#issuecomment-147854285.

## 

Zenoss Master, Tivoli Certified Consultant & Instructor
Skills 1st Limited, 2 Cedar Chase, Taplow, Bucks, SL6 0EU, UK.
Registered in England & Wales, Company No. 3458854.
Tel: +44 (0)1628 782565      Skype: jane_curry_uk
Email: jane.curry@skills-1st.co.uk   Web: http://www.skills-1st.co.uk
Copyright (c) 2015 Jane Curry < jane.curry@skills-1st.co.uk >.  All rights reserved.

**Comment by Mattikin** [comment]
Sounds good.

Now that you have changed the data source, as well as the modeler plugins, to utilize the python API, I'm wondering if it might make sense to integrate pyvmomi into the ZenPack?

Main advantages:
- No need to modify the zenhub container in Zenoss 5
- Installation of the ZenPack will be simplified
- Control over the pyvmomi version used

Disadvantage:
- Whenever a new pyvmomi version gets released the ZenPack will have to be updated

Your thoughts?

**Comment by jcurry** [comment]
I like the idea but not sure how you install a prereq as part of the 
ZenPack installation?  Do you know how to do that?

I had quite a fight to make pyvmomi work as I found that the latest 
version didn't work, hence the bundling of pyvmomi in the lib directory.

Cheers,
Jane

On 13/10/15 22:24, Mattikin wrote:

> Sounds good.
> 
> Now that you have changed the data source, as well as the modeler 
> plugins, to utilize the python API, I'm wondering if it might make 
> sense to integrate pyvmomi into the ZenPack?
> 
> Main advantages:
> - No need to modify the zenhub container in Zenoss 5
> - Installation of the ZenPack will be simplified
> - Control over the pyvmomi version used
> 
> Disadvantage:
> - Whenever a new pyvmomi version gets released the ZenPack will have
>   to be updated
> 
> Your thoughts?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1#issuecomment-147858413.

## 

Zenoss Master, Tivoli Certified Consultant & Instructor
Skills 1st Limited, 2 Cedar Chase, Taplow, Bucks, SL6 0EU, UK.
Registered in England & Wales, Company No. 3458854.
Tel: +44 (0)1628 782565      Skype: jane_curry_uk
Email: jane.curry@skills-1st.co.uk   Web: http://www.skills-1st.co.uk
Copyright (c) 2015 Jane Curry < jane.curry@skills-1st.co.uk >.  All rights reserved.

**Comment by jcurry** [comment]
I am using:
perl esxi_monitor.pl --server 10.0.0.33 --username root --password 
'notThis' --options 'guestperf:SWIDVM33'

but don't get any response - it eventually times out.  username and 
password are good.  Having put print statements into esxi_monitor.pl, it 
is timing out trying to get the perfmgr view. Any thoughts?

Cheers,
Jane

On 13/10/15 22:07, Mattikin wrote:

> Hey Jane,
> 
> I've looked into this and in my case the values reported by the old 
> and new ZenPack are exactly the same.
> 
> However I'm also using the modified data source. So maybe you can ask 
> your customer to upgrade to the latest version?
> 
> Also a good way to compare:
> In the new data source uncomment line 388-390 and run in debug mode
> In a second putty session run the esxi_monitor perl script (you only 
> need the vSphere SDK for perl + script, no need to actually install 
> the old ZenPack. As a matter of fact you don't even need Zenoss)
> You can run it like this:
> /usr/bin/perl esxi_monitor.pl --server --username --password '' 
> --options 'guestperf:'
> 
> I ran the new data source and the perl script at the same time and 
> received the exact same output:
> 
> {'adminStatus': 1, 'operStatus': 1, 'memUsage': 5.99, 'cpuUsageMin': 
> 0.54, 'cpuUsageMax': 0.54, 'cpuUsageAvg': 0.54, 'cpuUsage': 
> 57000000.0, 'memOverhead': 70447104.0, 'memConsumed': 1986183168.0, 
> 'diskUsage': 14336.0, 'powerState': 'poweredOn', 'overallStatus': 'green'}
> 
> memUsage=5.99 memOverhead=70447104 memConsumed=1986183168 
> diskUsage=14336 cpuUsageMin=0.54 cpuUsageMax=0.54 cpuUsageAvg=0.54 
> cpuUsage=57000000 adminStatus=1 operStatus=1
> 
> BTW: While I was testing this I've also noticed that you're adding the 
> "powerState" and "overallStatus" to the results dictionary, even 
> though there are no data points for those values.
> Are you doing this for debugging purposes?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1#issuecomment-147854285.

## 

Zenoss Master, Tivoli Certified Consultant & Instructor
Skills 1st Limited, 2 Cedar Chase, Taplow, Bucks, SL6 0EU, UK.
Registered in England & Wales, Company No. 3458854.
Tel: +44 (0)1628 782565      Skype: jane_curry_uk
Email: jane.curry@skills-1st.co.uk   Web: http://www.skills-1st.co.uk
Copyright (c) 2015 Jane Curry < jane.curry@skills-1st.co.uk >.  All rights reserved.

**Comment by Mattikin** [comment]
Are you using your Zenoss server, or some other server?

I'm wondering if it might be a problem with the firewall?!

**Comment by jcurry** [comment]
It's the zenoss server being used to run esxi_monitor.pl  It gets some 
data so it cannot fundamentally be firewalls.. I have put in some prints 
so, for example, it gets VM names, it gets their powerState but it times 
out when requesting the performance info - weird!

Any other thoughts?
Cheers,
Jane

On 15/10/15 17:26, Mattikin wrote:

> Are you using your Zenoss server, or some other server?
> 
> I'm wondering if it might be a firewall issue?!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/1#issuecomment-148444911.

## 

Zenoss Master, Tivoli Certified Consultant & Instructor
Skills 1st Limited, 2 Cedar Chase, Taplow, Bucks, SL6 0EU, UK.
Registered in England & Wales, Company No. 3458854.
Tel: +44 (0)1628 782565      Skype: jane_curry_uk
Email: jane.curry@skills-1st.co.uk   Web: http://www.skills-1st.co.uk
Copyright (c) 2015 Jane Curry < jane.curry@skills-1st.co.uk >.  All rights reserved.

**Pull request merged**
