### PR TITLE
The required pyvmomi python libraries are now delivered as part of the ZenPack

### PR DESCRIPTION
**Pull request by Mattikin**
Hey Jane,

During the installation of the ZenPack the pyvmomi libraries are now added to the python path variable.

Please let me know what you think.

Thanks.

### CODE REVIEW

**Comment by jcurry** [comment]
I have updated the master branch of the ZenPack with a slightly 
different BuildQuery system.  For my other customer, it appears to be 
getting much saner values.

Basically the maxSample parameter has been swapped for a StartTime / 
endTime pair with a sampling interval of 20s.  The maxSample method, for 
the other customer, was generally producing values about double what 
they should be!  I would be very interested to see what difference this 
change makes in your test environment.

I have also modified the gethostperfinfo.py in the samples directory to 
demonstrate the difference between the two.

Never did get your esxi_monitor.py to run successfully standalone and 
still don't know why :( so cannot compare yours with my old/new methods.

Not yest pulled your latest change with the pyvmomi change.  Does this 
actually install pyvmomi?  Not quite sure what the value is of just 
adding the lib path??

Many thanks for your continued interest on this.

Cheers,
Jane

On 15/10/15 17:09, Mattikin wrote:

> Hey Jane,
> 
> During the installation of the ZenPack the pyvmomi libraries are now 
> added to the python path variable.
> 
> Please let me know what you think.
> 
> Thanks.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/3
> 
> ```
>     Commit Summary
> ```
> - Merge remote-tracking branch 'refs/remotes/jcurry/master'
> - The required pyvmomi python libraries are now delivered as part of
>   the ZenPack
>   
>   ```
>   File Changes
>   ```
> - _M_ ZenPacks/community/VMwareESXiMonitorPython/**init**.py
>   https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/3/files#diff-0
>   (9)
> - _A_
>   ZenPacks/community/VMwareESXiMonitorPython/lib/pyvmomi-5.5.0-py2.7.egg
>   https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/3/files#diff-1
>   (0)
> - _D_
>   ZenPacks/community/VMwareESXiMonitorPython/lib/pyvmomi-5.5.0.zip
>   https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/3/files#diff-2
>   (0)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/3.patch
> - https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/3.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/3.

## 

Zenoss Master, Tivoli Certified Consultant & Instructor
Skills 1st Limited, 2 Cedar Chase, Taplow, Bucks, SL6 0EU, UK.
Registered in England & Wales, Company No. 3458854.
Tel: +44 (0)1628 782565      Skype: jane_curry_uk
Email: jane.curry@skills-1st.co.uk   Web: http://www.skills-1st.co.uk
Copyright (c) 2015 Jane Curry < jane.curry@skills-1st.co.uk >.  All rights reserved.

**Comment by Mattikin** [comment]
Hey Jane,

Thanks for the update. I'll give it a try.

It depends on what you mean by "installing" pyvmomi.

If you use easy_install, then all it will do is create the egg file, copy it to the site-packages directory and add it to the "easy-install.pth" file, which adds the egg file to the path variable of python.

My modifications just add the egg file in the lib directory of the ZenPack to the path variable of python.
Therefore it makes the libraries available to Zenoss.

So it's not required to install pyvmomi separately.

**Comment by jcurry** [comment]
So, just to make sure I really understand, with your latest 
modification, we don't need to have the prereq step of installing 
pyvmomi as it is made accessible by your mods to **init**.py, plus 
providing the egg ?????

Be interested in your experience with testing the new version.
Cheers,
Jane

On 16/10/15 15:39, Mattikin wrote:

> Hey Jane,
> 
> Thanks for the update. I'll give it a try.
> 
> It depends on what you mean by "installing" pyvmomi.
> 
> If you use easy_install, then all it will do is create the egg file, 
> copy it to the site-packages directory and add it to the 
> "easy-install.pth" file, which adds the egg file to the path variable 
> of python.
> 
> My modifications just add the egg file in the lib directory to the 
> path variable of python.
> Therefore it makes the libraries available for Zenoss.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jcurry/ZenPacks.community.VMwareESXiMonitorPython/pull/3#issuecomment-148734989.

## 

Zenoss Master, Tivoli Certified Consultant & Instructor
Skills 1st Limited, 2 Cedar Chase, Taplow, Bucks, SL6 0EU, UK.
Registered in England & Wales, Company No. 3458854.
Tel: +44 (0)1628 782565      Skype: jane_curry_uk
Email: jane.curry@skills-1st.co.uk   Web: http://www.skills-1st.co.uk
Copyright (c) 2015 Jane Curry < jane.curry@skills-1st.co.uk >.  All rights reserved.

**Comment by Mattikin** [comment]
That's correct, yes.

I'll provide an update later today.

I have already loaded your modified data source on my test system, but I still have to compare the raw values with the old version.

**Comment by Mattikin** [comment]
I'll leave it running over the weekend.

Haven't found any problems yet, but as you know it's hard to compare the values...

**Pull request merged**
